version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:7007"
    environment:
      - FLASK_ENV=development
      - OPENAI_API_KEY=
    volumes:
      - .:/app
    command: python app.py
